import type { ComponentType } from 'react';
import {
  FaFacebook,
  FaInstagram,
  FaTwitter,
  FaDiscord,
  FaGithub,
  FaHtml5,
  FaCss3Alt,
  FaJs,
  FaReact,
  FaNode,
  FaPython,
  FaDocker,
  FaLinkedin,
  FaAws,
  FaCloud,
  FaBrain,
  FaInfinity,
  FaDatabase,
  FaEye,
  FaCommentDots,
} from 'react-icons/fa';
import {
  SiTypescript,
  SiNextdotjs,
  SiTailwindcss,
  SiCplusplus,
  SiFastapi,
  SiPostgresql,
  SiSqlite,
  SiMongodb,
  SiRedis,
  SiVercel,
  SiNestjs,
  SiSupabase,
  SiFigma,
  SiMysql,
  SiRailway,
  SiExpress,
  SiPytorch,
  SiTensorflow,
  SiLangchain,
  SiOpenai,
  SiHuggingface,
} from 'react-icons/si';
import { VscCode } from 'react-icons/vsc';

type IconComponent = ComponentType<{ size?: string | number; className?: string }>;

// Social media icon mapping
export const SOCIAL_ICONS: Record<string, IconComponent> = {
  facebook: FaFacebook,
  instagram: FaInstagram,
  twitter: FaTwitter,
  discord: FaDiscord,
  github: FaGithub,
  linkedin: FaLinkedin,
};

// Technology icon mapping
export const TECH_ICONS: Record<string, IconComponent> = {
  docker: FaDocker,
  html: FaHtml5,
  css: FaCss3Alt,
  js: FaJs,
  javascript: FaJs,
  typescript: SiTypescript,
  ts: SiTypescript,
  react: FaReact,
  'next.js': SiNextdotjs,
  nextjs: SiNextdotjs,
  tailwindcss: SiTailwindcss,
  'node.js': FaNode,
  nodejs: FaNode,
  python: FaPython,
  'c++': SiCplusplus,
  cpp: SiCplusplus,
  nestjs: SiNestjs,
  fastapi: SiFastapi,
  supabase: SiSupabase,
  postgresql: SiPostgresql,
  sqlite: SiSqlite,
  mongodb: SiMongodb,
  redis: SiRedis,
  vercel: SiVercel,
  vscode: VscCode,
  'visual studio code': VscCode,
  github: FaGithub,
  'discord.py': FaDiscord,
  discordpy: FaDiscord,
  figma: SiFigma,
  mysql: SiMysql,
  railway: SiRailway,
  express: SiExpress,
  expressjs: SiExpress,
  'express.js': SiExpress,
  aws: FaAws,
  'cloud architecture': FaCloud,
  'ai/ml': FaBrain,
  devops: FaInfinity,
  'data engineering': FaDatabase,
  pytorch: SiPytorch,
  tensorflow: SiTensorflow,
  langchain: SiLangchain,
  'openai api': SiOpenai,
  'hugging face': SiHuggingface,
  nlp: FaCommentDots,
  'computer vision': FaEye,
};
